### ISSUE TITLE
Sub-Navigation menu.

### ISSUE THREAD

**Issue by ReconFlux** [datta-framework/dattatable#2]
having a sub-navigation menu to increases the discoverability of content in lower-level categories of your site architecture with the fewest number of clicks.

**Comment by gudatta** [comment]
Let's add onRender methods for each of the components. It'll give you the element containing the specific component, so you can render under it. Or insert it manually.

**Comment by gunjandatta** [comment]
You can use the "onRender" method to insert a sub-navigation. Added to v0.3.6.
